### ISSUE TITLE
Which countries count as european?

### ISSUE THREAD

**Issue by erictapen** [erictapen/mapping-migration#26]
Follow up to #23:

The question is, which countries exactly belong to europe, @herbertblb @yellowkobra @seragarez ?

I started by adding all member states of the EU in 8bffc93e276f53d308fbb4ebdea46df8d9ba21e1. That felt natural to me as our origin for the decision was the similiarities in the asylum bourocracies of european countries. The source (Wikipedia) is linked in the commit message.

If you think we should change that list, feel free to directly change [this file](https://github.com/erictapen/mapping-migration/blob/main/data/european-countries.json)! It serves as a "ground truth" to the application, as in changing the file directly changes what is selectable in the interface.

**Comment by seragarez** [comment]
Hey @erictapen ! @herbertblb, @Findus2000 and I stumbled upon that when looking at the app. I think we would rather have all European countries (as in the region of Europe) than just the EU. Maybe you can use all countries that fall under the region of Europe in the UNHCR data finder?
![grafik](https://user-images.githubusercontent.com/97115079/149203459-65c6bec3-71ca-4ef6-8715-4b470f3ed766.png)
![grafik](https://user-images.githubusercontent.com/97115079/149203503-da003f77-c707-498d-9e9c-3e7e43c9e411.png)

That would maybe be the easiest to argue, since we are using the UNHCR data anyway and that is the UNHCR's definition of the region of Europe. But I'm open to discuss it if you guys if you think otherwise :)

**Comment by erictapen** [comment]
Makes sense to me!
Thanks to the UNHCR API this was really easy to implement, so from now on the new list of countries should be used.
