### ISSUE TITLE
Layout / Fonts

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#34]
Is it possible to change for example the font used in the webapp? Because in my opinion it is too basic. But of course this is something for after the presentation

**Comment by erictapen** [comment]
Yes, that's still on my todo list. The font displayed currently is the default font of your web browser. Thanks for creating the issue for it!

**Comment by herbertblb** [comment]
Country names and subtitle (there were x decisions per bla inhabitants) in the top center

**Comment by erictapen** [comment]
We have a font! I chose [Karla](https://fonts.google.com/specimen/Karla) for now. I think it is somewhat "unausgeglichen", which I like about it
![font3](https://user-images.githubusercontent.com/11532355/155249887-e237a513-49b6-4784-a72f-3f2a6c6eabbc.png)
.

Let's see how it feels to work with it!

**Comment by herbertblb** [comment]
did you reconsider?

**Comment by erictapen** [comment]
@herbertblb What consideration are you referring to?

**Comment by erictapen** [comment]
The font isn't correctly rendered in Firefox? Look at the upper case G.

**Comment by erictapen** [comment]
Since f61fa5b01c2d17542497e8929163d6cd89342366, the font Karla should again be correctly rendered in every browser! Please ping me if you perceive otherwise. Remember to empty the site cache beforehand though.

Also font weight should be consistent now in every browser!

One characteristic letter I look at to see if it's the right font is the "2" in the year number. It should look like this:

![tmp FaXVnsJd7H](https://user-images.githubusercontent.com/11532355/155889729-961c1101-70a5-45c5-9d3d-878d70a895c5.png)
