### ISSUE TITLE
Implement animation

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#36]
make sketches for ways to animate the footprints and include missing migrants

**Comment by herbertblb** [comment]
see also #7

**Comment by herbertblb** [comment]
see our drafts on Miro

**Comment by erictapen** [comment]
We want to play the animation on any change of input, which means COO, COA1/2 and year.

**Comment by herbertblb** [comment]
Ist noch weitere Arbeit an der animation der Fußstapfen geplant? Auf KAthi und Séra wirkt es wie große Vogelschwärme, die reinfliegen, ein Eindruck, den wir ja nicht unbedingt erwecken wollen

**Comment by herbertblb** [comment]
und wie sieht es aus mit den Missing migrants? müssen wir darauf verzichten aus Zeitgründen?

**Comment by erictapen** [comment]
Ne, weder noch. Der aktuelle Stand ist nach wie vor work in progress. Ich versuche morgen vormittag das so umzusetzen wie in https://github.com/erictapen/mapping-migration/issues/36#issuecomment-1027029452 beschrieben.

**Comment by erictapen** [comment]
I finally got to implement the animation as described in https://github.com/erictapen/mapping-migration/issues/36#issuecomment-1027029452.

It took a lot of glue code to achieve this and I'm still not really satisfied with the implementation. It has quite a few shortcomings:

- The individual footprints can't react to each other (which would proabably be difficult anyway due to performance reasons)
- Their movement is completely independent from their destination, even though it might look like that from first glance. This is actually the result of a hack where I accessed the order in which they are rendered to offset the animation.

Still there are some knobs to turn: For every movement of a footstep it carries a state of `(direction, length, dt)`, where

- `direction` is the direction in which they move
- `length` is the distance they travel during the step
- `dt` is the time in milliseconds that is spent during the step

These three variables have a fixed starting value and are adapted during each step by adding a random number. By adapting the starting value and the characteristics of the random numbers it's possible to easily adapt the animation.

**Comment by erictapen** [comment]
Snaaap, completely forgot about missing migrants! Will implement that first thing tomorrow!

**Comment by erictapen** [comment]
Implemented the missing migrants footprint in de3e84f98ad16902921807c588e64a5a5194b804.

It got even more of a hack than the animation logic.

Currently the behaviour is like this: The MM animation is shown at the very first display of animation, not after that. The footprint wanders to a predefined position with a predefined movement.
If the user clicks on the info button, it opens the box. If the user clicks on the button again, the box vanishes irrevocably.
